#!/usr/bin/env python

bld.SAMBA_LIBRARY('dfs_server_ad',
                  source='dfs_server_ad.c',
                  deps='talloc-debug samdb samba-util LIBTSOCKET',
                  private_library=True
                  )
