#!/usr/bin/env python

bld.SAMBA_LIBRARY('cluster',
                  source='cluster.c local.c',
                  deps='dbwrap samba-hostconfig talloc-debug',
                  private_library=True
                  )

